apiVersion: batch/v1
kind: CronJob
metadata:
  name: ceph2aws-yourobject1
  namespace: your-kubernetes-namespace
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ceph2aws-yourobject1
            image: path/to/image/repository/ceph2aws:latest
            env:
            - name: ceph_bucket
              value: "ceph-bucket-name"
            - name: object_path
              value: "ceph-object-path"
            - name: aws_bucket
              value: "aws-bucket-name"
            - name: part_size
              value: "100"
            - name: max_parallel_processes
              value: "10"
            - name: tag
              value: "your-tag"
            - name: max_retries
              value: "5"
            - name: chunk_size
              value: "100"
            resources:
              requests:
                cpu: "10"
          restartPolicy: Never
          imagePullSecrets:
          - name: your-image-secret
